# Root configuration of the system
# For better readability, install a TOML syntax highlighting extension

name = "Android App Builder"  # Name of the system which is not compulsary and wont be shown anywhere
port = 8080   #Port to run the server on
base_path = "/home/cat/"      # Leave empty to use absolute path of the projects
log_path = "logs"   #Path to store logs, if project specific logs are not provided

[ssl]
enable_ssl = false
certificate_path = "cert.pem" # This are absolute path of the certificate and key
certificate_key_path = "key.pem" # This are absolute path of the certificate and key

# Root authentication (used if project-specific auth is not provided)
[auth]
auth_type = "address"        # Options: "token", "address" or "both"
address_type = "ip"          # Options: "ip", "hostname"
allowed_addresses = ["127.0.0.1", "::1", "192.168.1.100"] # can be ip or hostname not both
allowed_tokens = ["12345678901234567890123456789012"] # list of token if auth_type is token

[project]
allow_multi_build = true
max_pending_build = 10
# base_endpoint_path = "/api/school"
next_build_delay = 60


[project.build]
project_path = "/home/cat/school_build"
payload = [{type = "env", value = "aa", key = "tiger"}]
unique_build_key = "package_name"
on_success_failure = "http://127.0.0.1:8000/api/update/logs"
on_success_error_payload = [{type = "env", value = "aa", key = "tiger"}]
run_on_failure = []

[[project.build.run_on_success]]
command = "echo 1 && sleep 20"
title = "Running dummy logs"
send_to_sock = true

[[project.build.run_on_error]]
command = "echo 1 && sleep 20"
title = "Running dummy logs"
send_to_sock = true


[[project.build.commands]]
command = "echo 15 && sleep 20"
on_error = "abort"
title = "Running dummy logs"
send_to_sock = true

[[project.build.commands]]
command = "echo 2 && sleep 5"
title = "Running dummy logs"
send_to_sock = true

[[project.build.commands]]
command = "echo 3 && sleep 5"
title = "Running dummy logs"
send_to_sock = true

[[project.build.commands]]
command = "echo 3 && sleep 5"
title = "Running dummy logs"
send_to_sock = true

[[project.build.commands]]
command = "echo 4 && sleep 5"
title = "Running dummy logs"
send_to_sock = true

[[project.build.commands]]
command = "echo 5 && sleep 5"
title = "Last Step"
send_to_sock = true
